### ISSUE TITLE
Activate in Travis

### ISSUE THREAD

**Issue by jgsogo** [conan-community/conan-pistache#1]
Hi!

I've just added this repo here and I would want to get it running in CI, should we activate it in some common Travis account? should I connect it to my Travis account? ...?

Also, we need to change the CI badges.

Thanks!

**Comment by danimtb** [comment]
Travis CI should be activa now https://travis-ci.org/conan-community/conan-pistache and you should be able to manage it too.

**Comment by jgsogo** [comment]
:+1:
